# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "delicious-console"
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Mateus Prado"]
  s.date = "2012-09-15"
	s.default_executable = %q{delicious}
  s.description = "%Q{Store yours URL's on Delicious using your terminal console}"
  s.email = "mateus@mateusprado.com"
	s.executables = ["delicious"]
  s.extra_rdoc_files = [
    "README.md"
  ]
	s.files =[
		"Gemfile",
		"Rakefile",
		"README.MD",
		"VERSION",
		"bin/delicious",
		"lib/delicious-console.rb",
		"lib/delicious-console/authentication.rb",
		"lib/delicious-console/client.rb",
		"lib/delicious-console/console.rb",
		"lib/delicious-console/parser.rb",
		"spec/delicious-console_spec.rb",
		"spec/spec_helper.rb",
		
	]
  s.homepage = "http://github.com/mateusprado/delicious-console"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "%Q{A console application to Delicious Web Site}"
	s.test_files = [
		"spec/delicious-console_spec.rb",
		"spec/spec_helper.rb",
	]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<thor>, [">= 0"])
      s.add_runtime_dependency(%q<thor>, [">= 0.16.0"])
      s.add_development_dependency(%q<rspec>, [">= 2.11.0"])
    else
      s.add_dependency(%q<thor>, [">= 0"])
      s.add_dependency(%q<thor>, [">= 0.16.0"])
      s.add_dependency(%q<rspec>, [">= 2.11.0"])
    end
  else
    s.add_dependency(%q<thor>, [">= 0"])
    s.add_dependency(%q<thor>, [">= 0.16.0"])
    s.add_dependency(%q<rspec>, [">= 2.11.0"])
  end
end

